import {
  FieldType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
  defineObject,
} from 'twenty-sdk/define';

import {
  GEKTAR_MANAGER_ACTIVE_FIELD_ID,
  GEKTAR_MANAGER_EMAIL_FIELD_ID,
  GEKTAR_MANAGER_NAME_FIELD_ID,
  GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
  GEKTAR_MANAGER_ODOO_ID_FIELD_ID,
  GEKTAR_MANAGER_PHONE_FIELD_ID,
  GEKTAR_MANAGER_PLOTS_FIELD_ID,
  GEKTAR_MANAGER_TELEGRAM_CHAT_ID_FIELD_ID,
  GEKTAR_MANAGER_TELEGRAM_USERNAME_FIELD_ID,
  GEKTAR_MANAGER_REGION_FIELD_ID,
  GEKTAR_MANAGER_ROLE_FIELD_ID,
  GEKTAR_MANAGER_WORKSPACE_MEMBER_FIELD_ID,
  LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
  OPPORTUNITY_MANAGER_REVERSE_FIELD_ID,
  WORKSPACE_MEMBER_GEKTAR_MANAGERS_FIELD_ID,
} from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'gektarManager',
  namePlural: 'gektarManagers',
  labelSingular: 'Gektar Manager',
  labelPlural: 'Gektar Managers',
  description: 'Authorized manager responsible for Gektar investor leads',
  icon: 'IconUserStar',
  labelIdentifierFieldMetadataUniversalIdentifier: GEKTAR_MANAGER_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: GEKTAR_MANAGER_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: GEKTAR_MANAGER_ACTIVE_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'active',
      label: 'Active',
      icon: 'IconCircleCheck',
      defaultValue: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_ODOO_ID_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'odooId',
      label: 'Odoo ID',
      icon: 'IconDatabase',
      isNullable: true,
      isUnique: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_REGION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'region',
      label: 'Region',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_ROLE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'gektarRole',
      label: 'Role',
      icon: 'IconShield',
      defaultValue: "'MANAGER'",
      options: [
        { id: '9ba3562c-bf76-4bcf-846d-2e2d22ad6792', value: 'MANAGER', label: 'Manager', position: 0, color: 'blue' },
        { id: '0e40293c-cb41-412a-96d7-5365580198aa', value: 'ADMIN', label: 'Admin', position: 1, color: 'purple' },
      ],
    },
    {
      universalIdentifier: GEKTAR_MANAGER_EMAIL_FIELD_ID,
      type: FieldType.EMAILS,
      name: 'email',
      label: 'Email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_PHONE_FIELD_ID,
      type: FieldType.PHONES,
      name: 'phone',
      label: 'Phone',
      icon: 'IconPhone',
      isNullable: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_TELEGRAM_CHAT_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'telegramChatId',
      label: 'Telegram chat ID',
      icon: 'IconBrandTelegram',
      isNullable: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_TELEGRAM_USERNAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'telegramUsername',
      label: 'Telegram username',
      icon: 'IconBrandTelegram',
      isNullable: true,
    },
    {
      universalIdentifier: GEKTAR_MANAGER_WORKSPACE_MEMBER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'workspaceMember',
      label: 'Workspace member',
      icon: 'IconUserCog',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.workspaceMember.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        WORKSPACE_MEMBER_GEKTAR_MANAGERS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'workspaceMemberId',
      },
    },
    {
      universalIdentifier: GEKTAR_MANAGER_PLOTS_FIELD_ID,
      type: FieldType.RELATION,
      name: 'plots',
      label: 'Plots',
      icon: 'IconMap',
      relationTargetObjectMetadataUniversalIdentifier:
        LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        'd9f47f83-546b-43b9-9e42-65f0006e45fa',
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: OPPORTUNITY_MANAGER_REVERSE_FIELD_ID,
      type: FieldType.RELATION,
      name: 'opportunities',
      label: 'Opportunities',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        '5e32abf3-c2c5-4fff-918e-b1af9add9ae3',
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
