import {
  FieldType,
  OnDeleteAction,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import {
  GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
  LAND_PLOT_ADDRESS_FIELD_ID,
  LAND_PLOT_AREA_SOTKY_FIELD_ID,
  LAND_PLOT_CADASTRAL_NUMBER_FIELD_ID,
  LAND_PLOT_COVER_FIELD_ID,
  LAND_PLOT_DESCRIPTION_FIELD_ID,
  LAND_PLOT_ELECTRICITY_FIELD_ID,
  LAND_PLOT_GEOMETRY_FIELD_ID,
  LAND_PLOT_LATITUDE_FIELD_ID,
  LAND_PLOT_LIFECYCLE_FIELD_ID,
  LAND_PLOT_LONGITUDE_FIELD_ID,
  LAND_PLOT_MANAGER_FIELD_ID,
  LAND_PLOT_MEMBERSHIPS_FIELD_ID,
  LAND_PLOT_NAME_FIELD_ID,
  LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
  LAND_PLOT_OWNER_FIELD_ID,
  LAND_PLOT_OPPORTUNITIES_FIELD_ID,
  LAND_PLOT_ODOO_ID_FIELD_ID,
  LAND_PLOT_PRICE_PER_SOTKA_USD_FIELD_ID,
  LAND_PLOT_RAION_FIELD_ID,
  LAND_PLOT_REFERENCE_FIELD_ID,
  LAND_PLOT_REGION_FIELD_ID,
  LAND_PLOT_REZONE_STATUS_FIELD_ID,
  LAND_PLOT_RESERVED_UNTIL_FIELD_ID,
  LAND_PLOT_SETTLEMENT_FIELD_ID,
  LAND_PLOT_PHOTOS_FIELD_ID,
  LAND_PLOT_PRICE_USD_FIELD_ID,
  LAND_PLOT_REZONING_FIELD_ID,
  LAND_PLOT_SOIL_FIELD_ID,
  LAND_PLOT_WATER_FIELD_ID,
  LAND_PLOT_WORKSPACE_MEMBER_FIELD_ID,
  LAND_PLOT_VIDEOS_FIELD_ID,
  LAND_PLOT_WHY_THIS_PLOT_FIELD_ID,
  MEMBERSHIP_LAND_PLOT_FIELD_ID,
  OPPORTUNITY_LAND_PLOT_FIELD_ID,
  PERSON_LAND_PLOTS_FIELD_ID,
  PLOT_GROUP_MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER,
  WORKSPACE_MEMBER_LAND_PLOTS_FIELD_ID,
} from '../constants/universal-identifiers';
import { STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS } from 'twenty-sdk/define';

enum PlotLifecycle {
  DRAFT = 'DRAFT',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  UNAVAILABLE = 'UNAVAILABLE',
}

export default defineObject({
  universalIdentifier: LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'landPlot',
  namePlural: 'landPlots',
  labelSingular: 'Land Plot',
  labelPlural: 'Land Plots',
  description: 'Gektar land catalogue listing',
  icon: 'IconMapPin',
  labelIdentifierFieldMetadataUniversalIdentifier: LAND_PLOT_NAME_FIELD_ID,
  fields: [
    { universalIdentifier: LAND_PLOT_NAME_FIELD_ID, type: FieldType.TEXT, name: 'name', label: 'Name', icon: 'IconTag' },
    { universalIdentifier: LAND_PLOT_ODOO_ID_FIELD_ID, type: FieldType.NUMBER, name: 'odooId', label: 'Odoo ID', icon: 'IconDatabase', isNullable: true, isUnique: true },
    { universalIdentifier: LAND_PLOT_REFERENCE_FIELD_ID, type: FieldType.TEXT, name: 'reference', label: 'Reference', icon: 'IconHash', isNullable: true },
    { universalIdentifier: LAND_PLOT_CADASTRAL_NUMBER_FIELD_ID, type: FieldType.TEXT, name: 'cadastralNumber', label: 'Cadastral number', icon: 'IconFileCertificate', isUnique: true },
    { universalIdentifier: LAND_PLOT_AREA_SOTKY_FIELD_ID, type: FieldType.NUMBER, name: 'areaSotky', label: 'Area (sotky)', icon: 'IconRulerMeasure', isNullable: true },
    { universalIdentifier: LAND_PLOT_PRICE_USD_FIELD_ID, type: FieldType.CURRENCY, name: 'priceUsd', label: 'Price (USD)', icon: 'IconCurrencyDollar', isNullable: true },
    { universalIdentifier: LAND_PLOT_PRICE_PER_SOTKA_USD_FIELD_ID, type: FieldType.CURRENCY, name: 'pricePerSotkaUsd', label: 'Price per sotka (USD)', icon: 'IconCurrencyDollar', isNullable: true },
    { universalIdentifier: LAND_PLOT_ADDRESS_FIELD_ID, type: FieldType.ADDRESS, name: 'plotAddress', label: 'Location', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_REGION_FIELD_ID, type: FieldType.TEXT, name: 'region', label: 'Region', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_RAION_FIELD_ID, type: FieldType.TEXT, name: 'raion', label: 'Raion', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_SETTLEMENT_FIELD_ID, type: FieldType.TEXT, name: 'settlement', label: 'Settlement / locality', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_LATITUDE_FIELD_ID, type: FieldType.NUMBER, name: 'latitude', label: 'Latitude', icon: 'IconWorldLatitude', isNullable: true },
    { universalIdentifier: LAND_PLOT_LONGITUDE_FIELD_ID, type: FieldType.NUMBER, name: 'longitude', label: 'Longitude', icon: 'IconWorldLongitude', isNullable: true },
    { universalIdentifier: LAND_PLOT_GEOMETRY_FIELD_ID, type: FieldType.RAW_JSON, name: 'geometry', label: 'Geometry', icon: 'IconPolygon', isNullable: true },
    {
      universalIdentifier: LAND_PLOT_LIFECYCLE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'lifecycle',
      label: 'Lifecycle',
      icon: 'IconProgress',
      defaultValue: `'${PlotLifecycle.DRAFT}'`,
      options: [
        { id: 'e4e6e74e-35d6-4b47-8e48-74edd9771685', value: PlotLifecycle.DRAFT, label: 'Draft', position: 0, color: 'gray' },
        { id: '897f3d89-2770-41ff-9c72-34978e011c12', value: PlotLifecycle.AVAILABLE, label: 'Available', position: 1, color: 'green' },
        { id: '667d283d-7854-4730-841c-5b6b56e874eb', value: PlotLifecycle.RESERVED, label: 'Reserved', position: 2, color: 'orange' },
        { id: 'ff160337-cd46-4a8c-9d5f-e4f33c2c230f', value: PlotLifecycle.SOLD, label: 'Sold', position: 3, color: 'blue' },
        { id: 'a6dc1e97-d7bd-4d64-bcf2-2e9c74aa1777', value: PlotLifecycle.UNAVAILABLE, label: 'Unavailable', position: 4, color: 'brown' },
      ],
    },
    { universalIdentifier: LAND_PLOT_REZONING_FIELD_ID, type: FieldType.TEXT, name: 'rezoning', label: 'Rezoning', icon: 'IconBuildingCommunity', isNullable: true },
    {
      universalIdentifier: LAND_PLOT_REZONE_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'rezoneStatus',
      label: 'Rezone status',
      icon: 'IconBuildingCommunity',
      isNullable: true,
      options: [
        { id: '7f8c1227-176f-4c06-87b5-a6d14e824eff', value: 'PENDING', label: 'Pending', position: 0, color: 'gray' },
        { id: '5e5e9077-ef11-4f80-86b2-306395e0b28d', value: 'IN_PROGRESS', label: 'In progress', position: 1, color: 'orange' },
        { id: 'd076c34f-3734-4259-a6c3-96614d35ebd3', value: 'DONE', label: 'Done', position: 2, color: 'green' },
      ],
    },
    { universalIdentifier: LAND_PLOT_WHY_THIS_PLOT_FIELD_ID, type: FieldType.RAW_JSON, name: 'whyThisPlot', label: 'Why this plot', icon: 'IconBulb', isNullable: true },
    { universalIdentifier: LAND_PLOT_RESERVED_UNTIL_FIELD_ID, type: FieldType.DATE_TIME, name: 'reservedUntil', label: 'Reserved until', icon: 'IconClock', isNullable: true },
    { universalIdentifier: LAND_PLOT_SOIL_FIELD_ID, type: FieldType.TEXT, name: 'soil', label: 'Soil', icon: 'IconPlant', isNullable: true },
    { universalIdentifier: LAND_PLOT_WATER_FIELD_ID, type: FieldType.BOOLEAN, name: 'waterAvailable', label: 'Water available', icon: 'IconDroplet', isNullable: true },
    { universalIdentifier: LAND_PLOT_ELECTRICITY_FIELD_ID, type: FieldType.BOOLEAN, name: 'electricityAvailable', label: 'Electricity available', icon: 'IconBolt', isNullable: true },
    { universalIdentifier: LAND_PLOT_DESCRIPTION_FIELD_ID, type: FieldType.RICH_TEXT, name: 'description', label: 'Description', icon: 'IconMessage', isNullable: true },
    { universalIdentifier: LAND_PLOT_PHOTOS_FIELD_ID, type: FieldType.FILES, name: 'photos', label: 'Photos', icon: 'IconPhoto', isNullable: true, universalSettings: { maxNumberOfValues: 50 } },
    { universalIdentifier: LAND_PLOT_COVER_FIELD_ID, type: FieldType.FILES, name: 'cover', label: 'Cover', icon: 'IconPhoto', isNullable: true, universalSettings: { maxNumberOfValues: 1 } },
    { universalIdentifier: LAND_PLOT_VIDEOS_FIELD_ID, type: FieldType.FILES, name: 'videos', label: 'Videos', icon: 'IconVideo', isNullable: true, universalSettings: { maxNumberOfValues: 20 } },
    {
      universalIdentifier: LAND_PLOT_MANAGER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'manager',
      label: 'Manager',
      icon: 'IconUserStar',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: 'b43d0f82-7d06-436b-8ce2-3528a9abef12',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'managerId' },
    },
    {
      universalIdentifier: LAND_PLOT_OWNER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'owner',
      label: 'Owner / contact',
      icon: 'IconUser',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: PERSON_LAND_PLOTS_FIELD_ID,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'ownerId' },
    },
    {
      universalIdentifier: LAND_PLOT_WORKSPACE_MEMBER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'workspaceMember',
      label: 'Workspace member',
      icon: 'IconUserCog',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.workspaceMember.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: WORKSPACE_MEMBER_LAND_PLOTS_FIELD_ID,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'workspaceMemberId' },
    },
    {
      universalIdentifier: LAND_PLOT_MEMBERSHIPS_FIELD_ID,
      type: FieldType.RELATION,
      name: 'groupMemberships',
      label: 'Group memberships',
      icon: 'IconFolders',
      relationTargetObjectMetadataUniversalIdentifier: PLOT_GROUP_MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: MEMBERSHIP_LAND_PLOT_FIELD_ID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: LAND_PLOT_OPPORTUNITIES_FIELD_ID,
      type: FieldType.RELATION,
      name: 'opportunities',
      label: 'Opportunities',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        OPPORTUNITY_LAND_PLOT_FIELD_ID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
