import {
  FieldType,
  OnDeleteAction,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import {
  GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
  LAND_PLOT_AREA_SOTKY_FIELD_ID,
  LAND_PLOT_CADASTRAL_NUMBER_FIELD_ID,
  LAND_PLOT_COVER_FIELD_ID,
  LAND_PLOT_DESCRIPTION_FIELD_ID,
  LAND_PLOT_LATITUDE_FIELD_ID,
  LAND_PLOT_LIFECYCLE_FIELD_ID,
  LAND_PLOT_LONGITUDE_FIELD_ID,
  LAND_PLOT_MANAGER_FIELD_ID,
  LAND_PLOT_MEMBERSHIPS_FIELD_ID,
  LAND_PLOT_NAME_FIELD_ID,
  LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
  LAND_PLOT_OWNER_FIELD_ID,
  LAND_PLOT_OPPORTUNITIES_FIELD_ID,
  LAND_PLOT_ODOO_ID_FIELD_ID,
  LAND_PLOT_PRICE_PER_SOTKA_USD_FIELD_ID,
  LAND_PLOT_RAION_FIELD_ID,
  LAND_PLOT_REFERENCE_FIELD_ID,
  LAND_PLOT_REGION_SELECT_FIELD_ID,
  LAND_PLOT_REZONE_STATUS_FIELD_ID,
  LAND_PLOT_RESERVED_UNTIL_FIELD_ID,
  LAND_PLOT_SETTLEMENT_FIELD_ID,
  LAND_PLOT_PHOTOS_FIELD_ID,
  LAND_PLOT_PRICE_USD_FIELD_ID,
  LAND_PLOT_VIDEOS_FIELD_ID,
  LAND_PLOT_WHY_THIS_PLOT_FIELD_ID,
  MEMBERSHIP_LAND_PLOT_FIELD_ID,
  OPPORTUNITY_LAND_PLOT_FIELD_ID,
  PERSON_LAND_PLOTS_FIELD_ID,
  PLOT_GROUP_MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER,
} from '../constants/universal-identifiers';
import { STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS } from 'twenty-sdk/define';

enum PlotLifecycle {
  DRAFT = 'DRAFT',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  UNAVAILABLE = 'UNAVAILABLE',
}

export default defineObject({
  universalIdentifier: LAND_PLOT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'landPlot',
  namePlural: 'landPlots',
  labelSingular: 'Land Plot',
  labelPlural: 'Land Plots',
  description: 'Gektar land catalogue listing',
  icon: 'IconMapPin',
  labelIdentifierFieldMetadataUniversalIdentifier: LAND_PLOT_NAME_FIELD_ID,
  fields: [
    { universalIdentifier: LAND_PLOT_NAME_FIELD_ID, type: FieldType.TEXT, name: 'name', label: 'Name', icon: 'IconTag' },
    { universalIdentifier: LAND_PLOT_ODOO_ID_FIELD_ID, type: FieldType.NUMBER, name: 'odooId', label: 'Odoo ID', icon: 'IconDatabase', isNullable: true, isUnique: true },
    { universalIdentifier: LAND_PLOT_REFERENCE_FIELD_ID, type: FieldType.TEXT, name: 'reference', label: 'Reference', icon: 'IconHash', isNullable: true },
    { universalIdentifier: LAND_PLOT_CADASTRAL_NUMBER_FIELD_ID, type: FieldType.TEXT, name: 'cadastralNumber', label: 'Cadastral number', icon: 'IconFileCertificate', isUnique: true },
    { universalIdentifier: LAND_PLOT_AREA_SOTKY_FIELD_ID, type: FieldType.NUMBER, name: 'areaSotky', label: 'Area (sotky)', icon: 'IconRulerMeasure', isNullable: true },
    { universalIdentifier: LAND_PLOT_PRICE_USD_FIELD_ID, type: FieldType.CURRENCY, name: 'priceUsd', label: 'Price (USD)', icon: 'IconCurrencyDollar', isNullable: true },
    { universalIdentifier: LAND_PLOT_PRICE_PER_SOTKA_USD_FIELD_ID, type: FieldType.CURRENCY, name: 'pricePerSotkaUsd', label: 'Price per sotka (USD)', icon: 'IconCurrencyDollar', isNullable: true },
    {
      universalIdentifier: LAND_PLOT_REGION_SELECT_FIELD_ID,
      type: FieldType.SELECT,
      name: 'regionCode',
      label: 'Region',
      icon: 'IconMapPin',
      isNullable: true,
      options: [
        { id: '610a47e1-475a-46a6-bad9-5e869288a17e', value: 'VINNYTSIA', label: 'Vinnytsia Oblast', position: 0, color: 'gray' },
        { id: 'a9f7096c-2860-41a0-83b1-66242a4e6346', value: 'VOLYN', label: 'Volyn Oblast', position: 1, color: 'gray' },
        { id: 'b55af180-5d70-4543-bc06-c5126a61fd57', value: 'DNIPROPETROVSK', label: 'Dnipropetrovsk Oblast', position: 2, color: 'gray' },
        { id: '2fc6ffd0-6a15-44ad-8b38-eae0b732f13a', value: 'DONETSK', label: 'Donetsk Oblast', position: 3, color: 'gray' },
        { id: 'ed62baa8-8de9-4d1e-8928-0235426b8d75', value: 'ZHYTOMYR', label: 'Zhytomyr Oblast', position: 4, color: 'gray' },
        { id: '9c22d213-1e79-4363-bc2f-ef92f8a8b926', value: 'ZAKARPATTIA', label: 'Zakarpattia Oblast', position: 5, color: 'gray' },
        { id: '99143b2b-3401-4f00-b256-53836c464971', value: 'ZAPORIZHZHIA', label: 'Zaporizhzhia Oblast', position: 6, color: 'gray' },
        { id: 'eedd3e02-1858-463a-86fc-8bde9c60a71c', value: 'IVANO_FRANKIVSK', label: 'Ivano-Frankivsk Oblast', position: 7, color: 'gray' },
        { id: 'd6d0ed0e-681f-4f4f-a867-0821147c3b2e', value: 'KYIV', label: 'Kyiv Oblast', position: 8, color: 'gray' },
        { id: 'cc34f3b5-2c20-4058-b69c-ba8799fdb6a1', value: 'KIROVOHRAD', label: 'Kirovohrad Oblast', position: 9, color: 'gray' },
        { id: '145f4684-c576-4236-92e2-57ed8e2124aa', value: 'LUHANSK', label: 'Luhansk Oblast', position: 10, color: 'gray' },
        { id: '709190e7-9baf-4cc1-8440-5109f13c470b', value: 'LVIV', label: 'Lviv Oblast', position: 11, color: 'gray' },
        { id: '074821d9-01da-4191-bc09-bed88cef5b00', value: 'MYKOLAIV', label: 'Mykolaiv Oblast', position: 12, color: 'gray' },
        { id: '0765ae58-a8a4-4caa-9a67-6fa0d54d6386', value: 'ODESA', label: 'Odesa Oblast', position: 13, color: 'gray' },
        { id: 'e5a05e69-9435-4685-b44f-542b55e40c1f', value: 'POLTAVA', label: 'Poltava Oblast', position: 14, color: 'gray' },
        { id: '06f5c98b-d7ab-4ad6-a098-d209df17a2aa', value: 'RIVNE', label: 'Rivne Oblast', position: 15, color: 'gray' },
        { id: '1f985cea-2089-4dbd-9537-ad37e9b15b80', value: 'SUMY', label: 'Sumy Oblast', position: 16, color: 'gray' },
        { id: 'dd17e823-d223-4be2-b064-a06b2a30baa3', value: 'TERNOPIL', label: 'Ternopil Oblast', position: 17, color: 'gray' },
        { id: 'a3aff8b6-0cf4-47a5-abd1-df0bf8728273', value: 'KHARKIV', label: 'Kharkiv Oblast', position: 18, color: 'gray' },
        { id: '68bb7c4f-2da2-44b1-ae62-5a2689a66427', value: 'KHERSON', label: 'Kherson Oblast', position: 19, color: 'gray' },
        { id: '531b1097-623a-4bdb-ae59-ac1453719e46', value: 'KHMELNYTSKYI', label: 'Khmelnytskyi Oblast', position: 20, color: 'gray' },
        { id: '3551a241-e248-49bf-82b1-4fb729eed359', value: 'CHERKASY', label: 'Cherkasy Oblast', position: 21, color: 'gray' },
        { id: '431a7142-b4fc-45ed-beb6-5da98720c3fe', value: 'CHERNIVTSI', label: 'Chernivtsi Oblast', position: 22, color: 'gray' },
        { id: 'cae85324-f9a3-4876-8996-c8b739c3421f', value: 'CHERNIHIV', label: 'Chernihiv Oblast', position: 23, color: 'gray' },
        { id: '2a89ec89-52d3-49a0-9ad8-661f93fb13bf', value: 'CRIMEA', label: 'Autonomous Republic of Crimea', position: 24, color: 'gray' },
        { id: '0dab20d6-7f37-4666-9dfd-238f5dec4514', value: 'KYIV_CITY', label: 'Kyiv City', position: 25, color: 'blue' },
        { id: '06f2ae2c-6e56-4a6f-81ad-0016df94c747', value: 'SEVASTOPOL', label: 'Sevastopol City', position: 26, color: 'blue' },
      ],
    },
    { universalIdentifier: LAND_PLOT_RAION_FIELD_ID, type: FieldType.TEXT, name: 'raion', label: 'Raion', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_SETTLEMENT_FIELD_ID, type: FieldType.TEXT, name: 'settlement', label: 'Settlement / locality', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: LAND_PLOT_LATITUDE_FIELD_ID, type: FieldType.NUMBER, name: 'latitude', label: 'Latitude', icon: 'IconWorldLatitude', isNullable: true },
    { universalIdentifier: LAND_PLOT_LONGITUDE_FIELD_ID, type: FieldType.NUMBER, name: 'longitude', label: 'Longitude', icon: 'IconWorldLongitude', isNullable: true },
    {
      universalIdentifier: LAND_PLOT_LIFECYCLE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'lifecycle',
      label: 'Lifecycle',
      icon: 'IconProgress',
      defaultValue: `'${PlotLifecycle.DRAFT}'`,
      options: [
        { id: 'e4e6e74e-35d6-4b47-8e48-74edd9771685', value: PlotLifecycle.DRAFT, label: 'Draft', position: 0, color: 'gray' },
        { id: '897f3d89-2770-41ff-9c72-34978e011c12', value: PlotLifecycle.AVAILABLE, label: 'Available', position: 1, color: 'green' },
        { id: '667d283d-7854-4730-841c-5b6b56e874eb', value: PlotLifecycle.RESERVED, label: 'Reserved', position: 2, color: 'orange' },
        { id: 'ff160337-cd46-4a8c-9d5f-e4f33c2c230f', value: PlotLifecycle.SOLD, label: 'Sold', position: 3, color: 'blue' },
        { id: 'a6dc1e97-d7bd-4d64-bcf2-2e9c74aa1777', value: PlotLifecycle.UNAVAILABLE, label: 'Unavailable', position: 4, color: 'brown' },
      ],
    },
    {
      universalIdentifier: LAND_PLOT_REZONE_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'rezoneStatus',
      label: 'Rezone status',
      icon: 'IconBuildingCommunity',
      isNullable: true,
      options: [
        { id: '7f8c1227-176f-4c06-87b5-a6d14e824eff', value: 'PENDING', label: 'Pending', position: 0, color: 'gray' },
        { id: '5e5e9077-ef11-4f80-86b2-306395e0b28d', value: 'IN_PROGRESS', label: 'In progress', position: 1, color: 'orange' },
        { id: 'd076c34f-3734-4259-a6c3-96614d35ebd3', value: 'DONE', label: 'Done', position: 2, color: 'green' },
      ],
    },
    { universalIdentifier: LAND_PLOT_WHY_THIS_PLOT_FIELD_ID, type: FieldType.RAW_JSON, name: 'whyThisPlot', label: 'Why this plot', icon: 'IconBulb', isNullable: true },
    { universalIdentifier: LAND_PLOT_RESERVED_UNTIL_FIELD_ID, type: FieldType.DATE_TIME, name: 'reservedUntil', label: 'Reserved until', icon: 'IconClock', isNullable: true },
    { universalIdentifier: LAND_PLOT_DESCRIPTION_FIELD_ID, type: FieldType.RICH_TEXT, name: 'description', label: 'Description', icon: 'IconMessage', isNullable: true },
    { universalIdentifier: LAND_PLOT_PHOTOS_FIELD_ID, type: FieldType.FILES, name: 'photos', label: 'Photos', icon: 'IconPhoto', isNullable: true, universalSettings: { maxNumberOfValues: 50 } },
    { universalIdentifier: LAND_PLOT_COVER_FIELD_ID, type: FieldType.FILES, name: 'cover', label: 'Cover', icon: 'IconPhoto', isNullable: true, universalSettings: { maxNumberOfValues: 1 } },
    { universalIdentifier: LAND_PLOT_VIDEOS_FIELD_ID, type: FieldType.FILES, name: 'videos', label: 'Videos', icon: 'IconVideo', isNullable: true, universalSettings: { maxNumberOfValues: 20 } },
    {
      universalIdentifier: LAND_PLOT_MANAGER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'manager',
      label: 'Manager',
      icon: 'IconUserStar',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: GEKTAR_MANAGER_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: 'b43d0f82-7d06-436b-8ce2-3528a9abef12',
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'managerId' },
    },
    {
      universalIdentifier: LAND_PLOT_OWNER_FIELD_ID,
      type: FieldType.RELATION,
      name: 'owner',
      label: 'Owner / contact',
      icon: 'IconUser',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: PERSON_LAND_PLOTS_FIELD_ID,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'ownerId' },
    },
    {
      universalIdentifier: LAND_PLOT_MEMBERSHIPS_FIELD_ID,
      type: FieldType.RELATION,
      name: 'groupMemberships',
      label: 'Group memberships',
      icon: 'IconFolders',
      relationTargetObjectMetadataUniversalIdentifier: PLOT_GROUP_MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: MEMBERSHIP_LAND_PLOT_FIELD_ID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: LAND_PLOT_OPPORTUNITIES_FIELD_ID,
      type: FieldType.RELATION,
      name: 'opportunities',
      label: 'Opportunities',
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        OPPORTUNITY_LAND_PLOT_FIELD_ID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
